### ISSUE TITLE
Create all routes for Ingredient

### ISSUE THREAD

**Issue by TungTNg** [TungTNg/Groceries-Recipes-Meal-Plan-Backend#22]
Schema for Ingredient (create 1 ingredient) = 
{
    id,
    name,
    measurementType
}

**Comment by DianaxKang** [comment]
As a dev, I would like to have the routes for ingredients so that I can create, get, modify/update, delete the ingredients.

AC:
- [ ] Have a GET all ingredients route
- [ ] Have a GET ingredient by id
- [ ] Have a PUT ingredient
- [ ] Have a POST ingredient by id
- [ ] Have a DELETE ingredient by id
